server:
  port: 8080

spring:
  application:
    name: UserService
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: ConfigServer